# Site wide configuration

title: The Flypitch project
description: A formal proof of the independence of the continuum hypothesis
logo: flypitch2.svg
teaser:
locale:
baseurl:
url: https://flypitch.github.io
safe: true

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Jesse Han
  email:
  twitter:
  google:
  ad-client:
  ad-slot:
  bio:
  avatar:
disqus-shortname:


exclude: ["vendor", "lib", "tutorial", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json", "toc"]